export const SET_SONGS = 'SET_SONGS'
export const SET_SONGS_LOAD_STATUS = 'SET_SONGS_LOAD_STATUS'
export const INCREMENT_SONG_PAGE_COUNTER = 'INCREMENT_SONG_PAGE_COUNTER'
export const DECREMENT_SONG_PAGE_COUNTER = 'DECREMENT_SONG_PAGE_COUNTER'

export const SET_PROFILE = 'SET_PROFILE'
export const SET_PROFILE_X = 'SET_PROFILE_X'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'
export const SET_PROFILES = 'SET_PROFILES'
