export const SET_SONGS = 'SET_SONGS'
export const SET_SONGS_LOAD_STATUS = 'SET_SONGS_LOAD_STATUS'
//export const ADD_SONG_NAV_HISTORY = 'ADD_SONG_NAV_HISTORY'
export const SET_PREVIOUS_START_KEY = 'SET_PREVIOUS_START_KEY'
